/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan9;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yogi Arif Widodo <Yogi at scodeid.blogspot.com>
 */
public class AyamDiaEnak extends javax.swing.JFrame {
   int dragxMouse;
   int dragyMouse;
    private static final long serialVersionUID = 1L;
    
    //variable for decission logic
        private int cmbStatus;
        private int cmbLevel;
        private int cmbPaket; 
        private int cmbBuy;
        
    //perhitungan
        private double diskon;
        private int jumlahBeli;
        private double harga;
        private double totalBiaya;
        
    public AyamDiaEnak(int cmbStatus, int cmbLevel, int cmbPaket, int cmbBuy) {
        this.cmbStatus = cmbStatus;
        this.cmbLevel = cmbLevel;
        this.cmbPaket = cmbPaket;
        this.cmbBuy = cmbBuy;
    }
    /**
     * Creates new form AyamDiaEnak
     */
    public AyamDiaEnak() {
//        constructor for select comboBox
//        this.cmbStatus = (String) jCmbStatus.getSelectedItem();
//        league.setLeagueName(cmbStatus);
        initComponents();
        this.setBackground(new Color(0,0,0,0)); //drop shadow like as photoshop effect for side frame
        jikaOne();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabExit = new javax.swing.JLabel();
        jLabelChsOrder = new javax.swing.JLabel();
        jLabelBackgroundChooseOrder = new javax.swing.JLabel();
        jComboOrderWhat = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jStatusIsi = new javax.swing.JLabel();
        jLabelStatusBackground = new javax.swing.JLabel();
        jCmbStatus = new javax.swing.JComboBox<>();
        jJnsPaketIsi1 = new javax.swing.JLabel();
        jLabelPaketBackground = new javax.swing.JLabel();
        jCmbPaket = new javax.swing.JComboBox<>();
        jJnsLevelIsi2 = new javax.swing.JLabel();
        jLabelLevelBackground1 = new javax.swing.JLabel();
        jCmbLevel = new javax.swing.JComboBox<>();
        jLabelOthers = new javax.swing.JLabel();
        jLabeMuchBackground2 = new javax.swing.JLabel();
        jCmbBuy = new javax.swing.JComboBox<>();
        jBuy = new javax.swing.JButton();
        jTextTotalBuy = new javax.swing.JTextField();
        jTextJumBeli = new javax.swing.JTextField();
        jBtnRefresh = new javax.swing.JButton();
        jTextKeterangan = new javax.swing.JLabel();
        jTextHemat = new javax.swing.JLabel();
        jBtnRefresh1 = new javax.swing.JButton();
        jBtnRefresh2 = new javax.swing.JButton();
        jTextJumBeli1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabDragMous = new javax.swing.JLabel();
        jLabelBackgroundApps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/closecho.png"))); // NOI18N
        jLabExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabExitMouseReleased(evt);
            }
        });
        getContentPane().add(jLabExit);
        jLabExit.setBounds(6, 0, 20, 30);

        jLabelChsOrder.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelChsOrder.setText("Paha Ayam");
        getContentPane().add(jLabelChsOrder);
        jLabelChsOrder.setBounds(190, 250, 100, 30);

        jLabelBackgroundChooseOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_choose_order.png"))); // NOI18N
        jLabelBackgroundChooseOrder.setText("jLabel8");
        getContentPane().add(jLabelBackgroundChooseOrder);
        jLabelBackgroundChooseOrder.setBounds(60, 250, 220, 30);

        jComboOrderWhat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paha Ayam", "Sayap Ayam", "Ayam Hidup", "Ayam Siap Masak" }));
        jComboOrderWhat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboOrderWhatItemStateChanged(evt);
            }
        });
        jComboOrderWhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboOrderWhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboOrderWhatMouseExited(evt);
            }
        });
        jComboOrderWhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboOrderWhatActionPerformed(evt);
            }
        });
        getContentPane().add(jComboOrderWhat);
        jComboOrderWhat.setBounds(60, 250, 220, 26);

        jLabel6.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(223, 32, 311, 51);

        jLabel7.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(55, 378, 175, 51);

        jStatusIsi.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jStatusIsi.setText("Member");
        getContentPane().add(jStatusIsi);
        jStatusIsi.setBounds(180, 130, 80, 30);

        jLabelStatusBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_status.png"))); // NOI18N
        jLabelStatusBackground.setText("jLabel8");
        getContentPane().add(jLabelStatusBackground);
        jLabelStatusBackground.setBounds(60, 130, 220, 30);

        jCmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Non Member", "Belum Menikah ( Feature Locked )" }));
        jCmbStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbStatusItemStateChanged(evt);
            }
        });
        jCmbStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCmbStatusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCmbStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCmbStatusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCmbStatusMousePressed(evt);
            }
        });
        jCmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbStatusActionPerformed(evt);
            }
        });
        jCmbStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbStatusKeyPressed(evt);
            }
        });
        getContentPane().add(jCmbStatus);
        jCmbStatus.setBounds(60, 130, 217, 26);

        jJnsPaketIsi1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jJnsPaketIsi1.setText("Hemat 1");
        getContentPane().add(jJnsPaketIsi1);
        jJnsPaketIsi1.setBounds(310, 160, 100, 30);

        jLabelPaketBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_jenis_paket_1.png"))); // NOI18N
        jLabelPaketBackground.setText("jLabel8");
        getContentPane().add(jLabelPaketBackground);
        jLabelPaketBackground.setBounds(210, 160, 220, 30);

        jCmbPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hemat 1", "Hemat 2", "Dermawan ( Feature Locked )", "Nikah ( Feature Locked )" }));
        jCmbPaket.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbPaketItemStateChanged(evt);
            }
        });
        jCmbPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCmbPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCmbPaketMouseExited(evt);
            }
        });
        getContentPane().add(jCmbPaket);
        jCmbPaket.setBounds(210, 160, 210, 26);

        jJnsLevelIsi2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jJnsLevelIsi2.setText("Newbie");
        getContentPane().add(jJnsLevelIsi2);
        jJnsLevelIsi2.setBounds(180, 190, 100, 30);

        jLabelLevelBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_level_pembeli.png"))); // NOI18N
        jLabelLevelBackground1.setText("jLabel8");
        getContentPane().add(jLabelLevelBackground1);
        jLabelLevelBackground1.setBounds(60, 190, 220, 30);

        jCmbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Newbie", "Advance", "Mapan ( Feature Locked )" }));
        jCmbLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbLevelItemStateChanged(evt);
            }
        });
        jCmbLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCmbLevelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCmbLevelMouseExited(evt);
            }
        });
        getContentPane().add(jCmbLevel);
        jCmbLevel.setBounds(60, 190, 220, 26);

        jLabelOthers.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelOthers.setText("other");
        getContentPane().add(jLabelOthers);
        jLabelOthers.setBounds(350, 220, 100, 30);

        jLabeMuchBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_howmuch_buy.png"))); // NOI18N
        jLabeMuchBackground2.setText("jLabel8");
        getContentPane().add(jLabeMuchBackground2);
        jLabeMuchBackground2.setBounds(210, 220, 220, 30);

        jCmbBuy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "1 (Feature Locked)", "2 (Feature Locked)", "3 (Feature Locked)" }));
        jCmbBuy.setBorder(null);
        jCmbBuy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBuyItemStateChanged(evt);
            }
        });
        jCmbBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCmbBuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCmbBuyMouseExited(evt);
            }
        });
        jCmbBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBuyActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbBuy);
        jCmbBuy.setBounds(210, 220, 220, 26);

        jBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_buy_mouse_view.png"))); // NOI18N
        jBuy.setBorder(null);
        jBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBuyMouseExited(evt);
            }
        });
        jBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuyActionPerformed(evt);
            }
        });
        getContentPane().add(jBuy);
        jBuy.setBounds(471, 128, 168, 124);
        getContentPane().add(jTextTotalBuy);
        jTextTotalBuy.setBounds(260, 382, 379, 51);
        jTextTotalBuy.setForeground(new java.awt.Color(255, 255, 255));

        jTextTotalBuy.setBorder(null);

        jTextTotalBuy.setOpaque(false);

        jTextJumBeli.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextJumBeli.setText("Input Angka Jumlah Pembelian");
        jTextJumBeli.setToolTipText("");
        jTextJumBeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextJumBeliMouseClicked(evt);
            }
        });
        jTextJumBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextJumBeliActionPerformed(evt);
            }
        });
        jTextJumBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextJumBeliKeyTyped(evt);
            }
        });
        getContentPane().add(jTextJumBeli);
        jTextJumBeli.setBounds(60, 280, 190, 28);
        jTextJumBeli.setForeground(new java.awt.Color(255, 255, 255));

        jTextJumBeli.setBorder(null);

        jTextJumBeli.setOpaque(false);

        jBtnRefresh.setText("Refresh");
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRefresh);
        jBtnRefresh.setBounds(560, 440, 80, 28);

        jTextKeterangan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextKeterangan.setForeground(new java.awt.Color(255, 255, 255));
        jTextKeterangan.setText("Keterangan");
        getContentPane().add(jTextKeterangan);
        jTextKeterangan.setBounds(60, 480, 580, 16);

        jTextHemat.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextHemat.setForeground(new java.awt.Color(255, 255, 255));
        jTextHemat.setText("Anda Hemat");
        getContentPane().add(jTextHemat);
        jTextHemat.setBounds(60, 510, 300, 16);

        jBtnRefresh1.setText("Print");
        jBtnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefresh1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRefresh1);
        jBtnRefresh1.setBounds(560, 510, 80, 28);

        jBtnRefresh2.setText("Crytal Report");
        jBtnRefresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefresh2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRefresh2);
        jBtnRefresh2.setBounds(420, 510, 110, 28);

        jTextJumBeli1.setVisible(false);
        jTextJumBeli1.setText("Feature Locked");
        jTextJumBeli1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextJumBeli1MouseMoved(evt);
            }
        });
        jTextJumBeli1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTextJumBeli1MouseWheelMoved(evt);
            }
        });
        jTextJumBeli1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextJumBeli1MouseClicked(evt);
            }
        });
        getContentPane().add(jTextJumBeli1);
        jTextJumBeli1.setBounds(290, 310, 140, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paha Ayam", "Sayap Ayam", "Ayam Hidup", "Ayam Siap Masak" }));
        jComboBox2.setVisible(false);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(290, 280, 140, 26);

        jToggleButton1.setText("Tambah Order");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(470, 270, 160, 28);

        jToggleButton2.setText("Delete Tambah Order");
        jToggleButton2.setToolTipText("");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(470, 310, 160, 28);

        jLabDragMous.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabDragMousMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabDragMousMouseMoved(evt);
            }
        });
        getContentPane().add(jLabDragMous);
        jLabDragMous.setBounds(1, -4, 710, 570);

        jLabelBackgroundApps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_backgroundVersi2.1.png"))); // NOI18N
        jLabelBackgroundApps.setText("jLabel5");
        getContentPane().add(jLabelBackgroundApps);
        jLabelBackgroundApps.setBounds(-4, -4, 720, 570);

        setSize(new java.awt.Dimension(713, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbStatusActionPerformed
        
    }//GEN-LAST:event_jCmbStatusActionPerformed

    private void jBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuyActionPerformed
//          String itemText = (String) jComboStatus.getSelectedItem();
        if (jTextJumBeli.getText().trim().length() == 0) 
        {
            JOptionPane.showMessageDialog(null, "Field Jumlah Beli Tidak Boleh Kosong","Error 0x997", JOptionPane.WARNING_MESSAGE);
            jTextJumBeli.setText("Field ini (Numbers Only)");
        }
        jikaOne();
        //MEMBER
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        if (cmbStatus == 0)  // 0 is member
        {
            
//            JOptionPane.showMessageDialog(this, "hello 0");
            if (cmbLevel == 0)  //LEVEL - NEWBIE
            {
//                JOptionPane.showMessageDialog(this, "newbie");

//============NEWBIE COUNT WITH PAKET HEMAT 1 ==============================
                if (cmbPaket == 0)
                {
//                  JOptionPane.showMessageDialog(this, "Paket hemat 1");
                    //RP 12.500,-
                    harga = 12500;
                    
                    //=== GET JUMLAH BELI
                    String jumlahStringBuy = jTextJumBeli.getText();
                    jumlahBeli = Integer.parseInt(jumlahStringBuy);                    
                    //=== END GET JUMLAH BELI
                    
                    if (jumlahBeli > 3) 
                    {
                        //ctrl + click direct behaviour . . .
                        diskonyaMemberNew();
                    }
                    else
                    {
                        noDiskon();
                        jTextKeterangan.setText("TIP : Beli 3 ayam goreng, get 2.5% Discount");
                        jTextHemat.setVisible(false);
                    }          
                }
//============END OF NEWBIE COUNT WITH PAKET HEMAT 1 ========================

//============NEWBIE COUNT WITH PAKET HEMAT 2 ========================                
                else if (cmbPaket == 1)
                {
//                  JOptionPane.showMessageDialog(this, "Paket hemat 2");
                    //RP 17.500,-
                    harga = 17500;
                    
                    //=== GET JUMLAH BELI
                    String jumlahStringBuy = jTextJumBeli.getText();
                    jumlahBeli = Integer.parseInt(jumlahStringBuy);                    
                    //=== END GET JUMLAH BELI
                    
                    if (jumlahBeli > 3) 
                    {
                        //ctrl + click direct behaviour . . .
                        diskonyaMemberNew();
                    }
                    else
                    {
                        noDiskon();
                        jTextKeterangan.setText("TIP : Beli 3 ayam goreng, get 2.5% Discount");
                        jTextHemat.setVisible(false);
                    }
                }
//============END OF NEWBIE COUNT WITH PAKET HEMAT 2 ========================  
            }
            

            else if (cmbLevel == 1) //LEVEL - ADVANCE
            {
//              JOptionPane.showMessageDialog(this, "advance");

//============ADVANCE COUNT WITH PAKET HEMAT 1 ==============================

                if (cmbPaket == 0) //PAKET HEMAT 1
                {
//                  JOptionPane.showMessageDialog(this, "Paket hemat 1");
                    //RP 10.500,-
                    harga = 10500;
                    
                    //=== GET JUMLAH BELI
                    String jumlahStringBuy = jTextJumBeli.getText();
                    jumlahBeli = Integer.parseInt(jumlahStringBuy);                    
                    //=== END GET JUMLAH BELI
                    
                    if (jumlahBeli > 3) 
                    {
                        //ctrl + click direct behaviour . . .
                        diskonyaMemberAdv();
                    }
                    else
                    {
                        noDiskon();
                        jTextKeterangan.setText("TIP : Beli 3 ayam goreng, get 2.5% Discount");
                        jTextHemat.setVisible(false);
                    }
                }
                
//============END OF ADVANCE COUNT WITH PAKET HEMAT 1 ==============================
                
//============ADVANCE COUNT WITH PAKET HEMAT 2 =====================================
                else if (cmbPaket == 1) //PAKET HEMAT 2
                {
//                  JOptionPane.showMessageDialog(this, "Paket hemat 2");
                    //RP 15.500,-
                    harga = 15500;
                    
                    //=== GET JUMLAH BELI
                    String jumlahStringBuy = jTextJumBeli.getText();
                    jumlahBeli = Integer.parseInt(jumlahStringBuy);                    
                    //=== END GET JUMLAH BELI
                    
                    if (jumlahBeli > 3) 
                    {
                        //ctrl + click direct behaviour . . .
                        diskonyaMemberAdv();
                    }
                    else
                    {
                        noDiskon();
                        jTextKeterangan.setText("TIP : Beli 3 ayam goreng, get 2.5% Discount");
                        jTextHemat.setVisible(false);
                    }
                }
//============ADVANCE COUNT WITH PAKET HEMAT 2 =====================================
            }
        }
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        //NON - MEMBER
        else if (cmbStatus == 1) 
        {
//            JOptionPane.showMessageDialog(this, "hello 1");
            
//==================COUNT OF PAKET HEMAT 1=========================================================
              if (cmbPaket == 0)
                {
//                  JOptionPane.showMessageDialog(this, "Paket hemat 1");
                    //RP 15.500,-
                    harga = 15500;
                    
                    //=== GET JUMLAH BELI
                    String jumlahStringBuy = jTextJumBeli.getText();
                    jumlahBeli = Integer.parseInt(jumlahStringBuy);                    
                    //=== END GET JUMLAH BELI
                    
                    if (jumlahBeli > 3) 
                    {
                        //ctrl + click direct behaviour . . .
                        diskonyaNonMember();
                    }
                    else
                    {
                        noDiskon();
                        jTextKeterangan.setText("TIP : Beli 3 ayam goreng, get 2.5% Discount");
                        jTextHemat.setVisible(false);
                    }                    
                }
//==================END OF PAKET HEMAT 1=========================================================
              
              
//==================COUNT OF PAKET HEMAT 2=========================================================
                else if (cmbPaket == 1)
                {
//                  JOptionPane.showMessageDialog(this, "Paket hemat 2");
                    //RP 20.500,-
                    harga = 20500;
                    
                    //=== GET JUMLAH BELI
                    String jumlahStringBuy = jTextJumBeli.getText();
                    jumlahBeli = Integer.parseInt(jumlahStringBuy);                    
                    //=== END GET JUMLAH BELI
                    
                    if (jumlahBeli > 3) 
                    {
                        diskonyaNonMember();
                    }
                    else
                    {
                        noDiskon();
                        jTextKeterangan.setText("TIP : Beli 3 ayam goreng, get 2.5% Discount");
                        jTextHemat.setVisible(false);
                    }
                }
              
//==================COUNT OF PAKET HEMAT 2=========================================================

        }
    }//GEN-LAST:event_jBuyActionPerformed

//================EVENT CHANGE COMBO BOX STATE ============================================       
    private void jCmbStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbStatusItemStateChanged
        jikaOne();
        if (cmbStatus == 1) 
        {
//            jCmbLevel.setVisible(false);
              jCmbLevel.disable();
              jLabelLevelBackground1.disable();
              jJnsLevelIsi2.disable();
//            jLabel2.setVisible(false);
            
        }
//        else if(cmbStatus == 3)
//        {
//            jCmbLevel.disable();
//            jCmbPaket.disable();
//            jCmbBuy.disable();
//        }
        else
        {
            jJnsLevelIsi2.enable();
            jCmbLevel.enable();
            jLabelLevelBackground1.enable();
        }
        jStatusIsi.setText(""+jCmbStatus.getSelectedItem());
    }//GEN-LAST:event_jCmbStatusItemStateChanged

    private void jCmbBuyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBuyItemStateChanged
        
        jikaOne();
        if (cmbBuy == 0) 
        {
            jTextJumBeli.setVisible(true);
        }
        else
        {
            jTextJumBeli.setVisible(false);
        }
        jLabelOthers.setText(""+jCmbBuy.getSelectedItem());
        
    }//GEN-LAST:event_jCmbBuyItemStateChanged

//================END OF EVENT CHANGE COMBO BOX STATE ============================================       
    
    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        revalidate();
        doLayout();
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    private void jBtnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefresh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRefresh1ActionPerformed

    private void jBtnRefresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefresh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRefresh2ActionPerformed

    private void jTextJumBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextJumBeliActionPerformed
       
    }//GEN-LAST:event_jTextJumBeliActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       jTextJumBeli1.setVisible(true);
       jComboBox2.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        jTextJumBeli1.setVisible(false);
       jComboBox2.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextJumBeli1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTextJumBeli1MouseWheelMoved
        
    }//GEN-LAST:event_jTextJumBeli1MouseWheelMoved

    private void jTextJumBeli1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextJumBeli1MouseMoved

    }//GEN-LAST:event_jTextJumBeli1MouseMoved

    private void jTextJumBeli1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextJumBeli1MouseClicked
       
    }//GEN-LAST:event_jTextJumBeli1MouseClicked

    private void jComboOrderWhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboOrderWhatActionPerformed
        
    }//GEN-LAST:event_jComboOrderWhatActionPerformed

    private void jCmbStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbStatusMouseClicked
            
    }//GEN-LAST:event_jCmbStatusMouseClicked

    private void jBuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuyMouseEntered
       ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_buy.png"));
       jBuy.setIcon(yogiAsset);
    }//GEN-LAST:event_jBuyMouseEntered

    private void jBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuyMouseExited
        ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/ayamenak_buy_mouse_view.png"));
       jBuy.setIcon(yogiAsset);
    }//GEN-LAST:event_jBuyMouseExited

    private void jBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuyMouseClicked
       
    }//GEN-LAST:event_jBuyMouseClicked

    private void jTextJumBeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextJumBeliKeyTyped
        // TODO add your handling code here: io num only
        char enterIo = evt.getKeyChar();
        if (!(Character.isDigit(enterIo))) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextJumBeliKeyTyped

    private void jCmbStatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbStatusKeyPressed
        
    }//GEN-LAST:event_jCmbStatusKeyPressed

    private void jCmbStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbStatusMouseEntered
       jLabelStatusBackground.hide();
    }//GEN-LAST:event_jCmbStatusMouseEntered

    private void jCmbStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbStatusMouseExited
     jLabelStatusBackground.show();
     
    }//GEN-LAST:event_jCmbStatusMouseExited

    private void jCmbStatusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbStatusMousePressed
        
    }//GEN-LAST:event_jCmbStatusMousePressed

    private void jCmbPaketItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbPaketItemStateChanged
        jJnsPaketIsi1.setText(""+jCmbPaket.getSelectedItem());
    }//GEN-LAST:event_jCmbPaketItemStateChanged

    private void jCmbPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbPaketMouseEntered
        jLabelPaketBackground.hide();
    }//GEN-LAST:event_jCmbPaketMouseEntered

    private void jCmbPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbPaketMouseExited
       jLabelPaketBackground.show();
    }//GEN-LAST:event_jCmbPaketMouseExited

    private void jCmbLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbLevelItemStateChanged
        jJnsLevelIsi2.setText(""+jCmbLevel.getSelectedItem());
    }//GEN-LAST:event_jCmbLevelItemStateChanged

    private void jCmbLevelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbLevelMouseEntered
       jLabelLevelBackground1.hide();
    }//GEN-LAST:event_jCmbLevelMouseEntered

    private void jCmbLevelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbLevelMouseExited
       jLabelLevelBackground1.show();
    }//GEN-LAST:event_jCmbLevelMouseExited

    private void jCmbBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBuyActionPerformed

    private void jCmbBuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbBuyMouseEntered
        jLabeMuchBackground2.hide();
    }//GEN-LAST:event_jCmbBuyMouseEntered

    private void jCmbBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbBuyMouseExited
        jLabeMuchBackground2.show();
    }//GEN-LAST:event_jCmbBuyMouseExited

    private void jComboOrderWhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboOrderWhatMouseEntered
      jLabelBackgroundChooseOrder.hide();
    }//GEN-LAST:event_jComboOrderWhatMouseEntered

    private void jComboOrderWhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboOrderWhatMouseExited
        jLabelBackgroundChooseOrder.show();
    }//GEN-LAST:event_jComboOrderWhatMouseExited

    private void jComboOrderWhatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboOrderWhatItemStateChanged
      jLabelChsOrder.setText(""+jComboOrderWhat.getSelectedItem());
      int cmbOrder = jComboOrderWhat.getSelectedIndex();
        if (cmbOrder == 0) 
        {
            ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/paha_ayam_orderan.png"));
            jLabDragMous.setIcon(yogiAsset);
        }
        else if (cmbOrder == 1) 
        {
            ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/sayap_ayam_orderan.png"));
            jLabDragMous.setIcon(yogiAsset);
        }
        else if (cmbOrder == 2) 
        {
            ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/ayam_hidup_orderan.png"));
            jLabDragMous.setIcon(yogiAsset);
        }
        else if (cmbOrder == 3) 
        {
            ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/paha_ayam_orderan.png"));
            jLabDragMous.setIcon(yogiAsset);
        }
    }//GEN-LAST:event_jComboOrderWhatItemStateChanged

    private void jLabExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabExitMouseClicked

    private void jLabExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabExitMouseEntered
        ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/close.png"));
        jLabExit.setIcon(yogiAsset);
    }//GEN-LAST:event_jLabExitMouseEntered

    private void jLabExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabExitMouseExited
        ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/closecho.png"));
        jLabExit.setIcon(yogiAsset);
    }//GEN-LAST:event_jLabExitMouseExited

    private void jLabExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabExitMousePressed
         ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/close.png"));
        jLabExit.setIcon(yogiAsset);
    }//GEN-LAST:event_jLabExitMousePressed

    private void jLabExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabExitMouseReleased
         ImageIcon yogiAsset = new ImageIcon(getClass().getResource("/pertemuan9/images/closec.png"));
        jLabExit.setIcon(yogiAsset);
    }//GEN-LAST:event_jLabExitMouseReleased

    private void jLabDragMousMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabDragMousMouseDragged
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxMouse, y - dragyMouse);
    }//GEN-LAST:event_jLabDragMousMouseDragged

    private void jLabDragMousMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabDragMousMouseMoved
         dragxMouse = evt.getX();
        dragyMouse = evt.getY();
    }//GEN-LAST:event_jLabDragMousMouseMoved

    private void jTextJumBeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextJumBeliMouseClicked
        jTextJumBeli.setText("");
    }//GEN-LAST:event_jTextJumBeliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AyamDiaEnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AyamDiaEnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AyamDiaEnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AyamDiaEnak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form WITH LAMBDA */
        java.awt.EventQueue.invokeLater(() -> {
            //                new AyamDiaEnak().jTextJumBeli.setVisible(false);
            new AyamDiaEnak().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JButton jBtnRefresh1;
    private javax.swing.JButton jBtnRefresh2;
    private javax.swing.JButton jBuy;
    private javax.swing.JComboBox<String> jCmbBuy;
    private javax.swing.JComboBox<String> jCmbLevel;
    private javax.swing.JComboBox<String> jCmbPaket;
    private javax.swing.JComboBox<String> jCmbStatus;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboOrderWhat;
    private javax.swing.JLabel jJnsLevelIsi2;
    private javax.swing.JLabel jJnsPaketIsi1;
    private javax.swing.JLabel jLabDragMous;
    private javax.swing.JLabel jLabExit;
    private javax.swing.JLabel jLabeMuchBackground2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBackgroundApps;
    private javax.swing.JLabel jLabelBackgroundChooseOrder;
    private javax.swing.JLabel jLabelChsOrder;
    private javax.swing.JLabel jLabelLevelBackground1;
    private javax.swing.JLabel jLabelOthers;
    private javax.swing.JLabel jLabelPaketBackground;
    private javax.swing.JLabel jLabelStatusBackground;
    private javax.swing.JLabel jStatusIsi;
    private javax.swing.JLabel jTextHemat;
    private javax.swing.JTextField jTextJumBeli;
    private javax.swing.JTextField jTextJumBeli1;
    private javax.swing.JLabel jTextKeterangan;
    private javax.swing.JTextField jTextTotalBuy;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
    
//===========get index comboBox for decission=========================================
    private void jikaOne()
    {
      this.cmbStatus = jCmbStatus.getSelectedIndex();
      this.cmbPaket = jCmbPaket.getSelectedIndex();
      this.cmbLevel = jCmbLevel.getSelectedIndex();
      this.cmbBuy = jCmbBuy.getSelectedIndex();
    }
//===========end of get index comboBox for decission==================================
    
    
//===============function count strategy bussiness====================================
    private double totalBayarFunction(double diskon, int jumlahBeli, double harga)
    {
        totalBiaya = (1 - diskon) * (jumlahBeli * harga);
        
        return totalBiaya;
    }
//===============function count strategy bussiness====================================
    
    private void kursConvert()
    {
        String mataUang = String.format("Rp.%,.0f",+totalBayarFunction(diskon, jumlahBeli, harga)).replaceAll(",",".")+",00";
        jTextTotalBuy.setText(mataUang);
    }
    private void kursConvertAwal()
    {
        String mataUang = String.format("Rp.%,.0f",+totalBayarFunction(diskon, jumlahBeli, harga)).replaceAll(",",".")+",00";
        jTextHemat.setText("Tagihan Awal : "+mataUang);
    }
//==========ALL WITH NO DISKON =======================================================
    
    private void noDiskon()
    {
        diskon = 0;
        //PERHITUNGAN and SET HASIL 
        kursConvert();
    }
//============END OF WITH NO DISKON ==================================================
    
    
//============DISKON NON MEMBER PAKET 1 DAN 2 ========================================
    private void diskonyaNonMember()
    {
        diskon = 2.5/100;
        //PERHITUNGAN and SET HASIL                   
        kursConvert();
        jTextKeterangan.setText("Selamat anda mendapatkan diskon 2.5% , karena membeli lebih dari 3 ayam goreng.");
                        
        jTextHemat.setVisible(true);
        diskon = 0;
        kursConvertAwal();
    }
//============END OF DISKON NON MEMBER PAKET 1 DAN 2 ========================================
    
//============DISKON NON MEMBER PAKET 1 DAN 2 ========================================
    private void diskonyaMemberNew()
    {
        diskon = 0.05;
        //PERHITUNGAN and SET HASIL
        kursConvert();
        jTextKeterangan.setText("Selamat anda mendapatkan diskon 5% , karena membeli lebih dari 3 ayam goreng.");
                        
        jTextHemat.setVisible(true);
        diskon = 0;
        jTextHemat.setText("Tagihan Awal : "+totalBayarFunction(diskon, jumlahBeli, harga));
    }
//============END OF DISKON NON MEMBER PAKET 1 DAN 2 ========================================
    
//============DISKON NON MEMBER PAKET 1 DAN 2 ========================================
    private void diskonyaMemberAdv()
    {
        diskon = 0.15;
        //PERHITUNGAN and SET HASIL                   
        kursConvert();
        jTextKeterangan.setText("Selamat anda mendapatkan diskon 15% , karena membeli lebih dari 3 ayam goreng.");
                        
        jTextHemat.setVisible(true);
        diskon = 0;
        jTextHemat.setText("Tagihan Awal : "+totalBayarFunction(diskon, jumlahBeli, harga));
    }
//============END OF DISKON NON MEMBER PAKET 1 DAN 2 ========================================
    
    //encapsulation field with get and setter
    /**
     * @return the cmbStatus
     */
    public int getCmbStatus() {
        return cmbStatus;
    }

    /**
     * @param cmbStatus the cmbStatus to set
     */
    public void setCmbStatus(int cmbStatus) {
        this.cmbStatus = cmbStatus;
    }

    /**
     * @return the cmbLevel
     */
    public int getCmbLevel() {
        return cmbLevel;
    }

    /**
     * @param cmbLevel the cmbLevel to set
     */
    public void setCmbLevel(int cmbLevel) {
        this.cmbLevel = cmbLevel;
    }

    /**
     * @return the cmbPaket
     */
    public int getCmbPaket() {
        return cmbPaket;
    }

    /**
     * @param cmbPaket the cmbPaket to set
     */
    public void setCmbPaket(int cmbPaket) {
        this.cmbPaket = cmbPaket;
    }

}
